### ISSUE TITLE
Subtract Numbers API

### ISSUE THREAD

**Issue by krist00fer** [krist00fer/calc-test#2]
The Calculator Service need an API to subtract two numbers. Create an REST-ful endpoint that given a HTTP Post request with the following payload:

{ "value1":666, "value2":777 }

> 666 and 777 in the above examples are placeholders for any integer number

... should return the dif of value1 and value2

**Comment by syedhassaanahmed** [comment]
On it

**Comment by simonjaeger** [comment]
Sorry, on it!

**Comment by simonjaeger** [comment]
See #3 please.

**Comment by krist00fer** [comment]
Closing since PR #3 solved this issue
